scope: patroni
name: 10.0.0.11
restapi:
  listen: 10.0.0.11:8008
  connect_address: 10.0.0.11:8008
etcd:
  hosts: 10.0.0.13:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_mode_count: 1
    master_start_timeout: 30
    postgresql:
      use_pg_rewind: true
      parameters:
        shared_buffers: '512MB'
        wal_level: 'replica'
        wal_keep_size: '512MB'
        max_connections: 100
        effective_cache_size: '1GB'
        maintenance_work_mem: '256MB'
        max_wal_senders: 5
        max_replication_slots: 5
        synchronous_commit: 'on'
        synchronous_standby_names: '*'
        hot_standby: 'on'
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 10.0.0.0/24 scram-sha-256
    - host all all 10.0.0.0/24 scram-sha-256
  users:
    admin:
      password: admin_321
      options:
        - createrole
        - createdb
postgresql:
  listen: 127.0.0.1, 10.0.0.11:5432
  connect_address: 10.0.0.11:5432
  data_dir: /var/lib/postgresql/17/main
  bin_dir: /usr/lib/postgresql/17/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass_321
    superuser:
      username: postgres
      password: postgres
    rewind:
      username: rewind_user
      password: rewind_password_321
  parameters:
    unix_socket_directories: '.'
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false